FrozenTrial(
    number=32,
    values=[0.4498437481762916],
    datetime_start=datetime.datetime(2022, 10, 19, 18, 46, 46, 757736),
    datetime_complete=datetime.datetime(2022, 10, 19, 18, 48, 18, 936458),
    params={
        "head_regressor": "BayesianRidge",
        "num_stacks": 5,
        "stack_0": "DebertaV3Large",
        "stack_1": "T5Large",
        "stack_2": "AllMiniLML6v2",
        "stack_3": "T5V1Base",
        "stack_4": "DebertaV3",
    },
    distributions={
        "head_regressor": CategoricalDistribution(
            choices=(
                "BayesianRidge",
                "ElasticNet",
                "OrthogonalMatchingPursuit",
                "SGDRegressor",
                "RidgeCV",
                "LassoCV",
                "SVR",
                "AdaBoostRegressor",
                "GradientBoostingRegressor",
                "RandomForestRegressor",
            )
        ),
        "num_stacks": IntDistribution(high=5, log=False, low=1, step=1),
        "stack_0": CategoricalDistribution(
            choices=(
                "AllMiniLML6v2",
                "AllMiniLML6v2",
                "AllMpnetBasev2",
                "AllMpnetBasev1",
                "AllDistilrobertaV1",
                "RobertaLarge",
                "BertBaseUncased",
                "DebertaV3",
                "DebertaV3Large",
                "DebertaV3Small",
                "DebertaV3XSmall",
                "BartBase",
                "BartLarge",
                "AlbertV2",
                "T5Base",
                "T5Large",
                "T5V1Base",
                "T5V1Large",
            )
        ),
        "stack_1": CategoricalDistribution(
            choices=(
                "AllMiniLML6v2",
                "AllMiniLML6v2",
                "AllMpnetBasev2",
                "AllMpnetBasev1",
                "AllDistilrobertaV1",
                "RobertaLarge",
                "BertBaseUncased",
                "DebertaV3",
                "DebertaV3Large",
                "DebertaV3Small",
                "DebertaV3XSmall",
                "BartBase",
                "BartLarge",
                "AlbertV2",
                "T5Base",
                "T5Large",
                "T5V1Base",
                "T5V1Large",
            )
        ),
        "stack_2": CategoricalDistribution(
            choices=(
                "AllMiniLML6v2",
                "AllMiniLML6v2",
                "AllMpnetBasev2",
                "AllMpnetBasev1",
                "AllDistilrobertaV1",
                "RobertaLarge",
                "BertBaseUncased",
                "DebertaV3",
                "DebertaV3Large",
                "DebertaV3Small",
                "DebertaV3XSmall",
                "BartBase",
                "BartLarge",
                "AlbertV2",
                "T5Base",
                "T5Large",
                "T5V1Base",
                "T5V1Large",
            )
        ),
        "stack_3": CategoricalDistribution(
            choices=(
                "AllMiniLML6v2",
                "AllMiniLML6v2",
                "AllMpnetBasev2",
                "AllMpnetBasev1",
                "AllDistilrobertaV1",
                "RobertaLarge",
                "BertBaseUncased",
                "DebertaV3",
                "DebertaV3Large",
                "DebertaV3Small",
                "DebertaV3XSmall",
                "BartBase",
                "BartLarge",
                "AlbertV2",
                "T5Base",
                "T5Large",
                "T5V1Base",
                "T5V1Large",
            )
        ),
        "stack_4": CategoricalDistribution(
            choices=(
                "AllMiniLML6v2",
                "AllMiniLML6v2",
                "AllMpnetBasev2",
                "AllMpnetBasev1",
                "AllDistilrobertaV1",
                "RobertaLarge",
                "BertBaseUncased",
                "DebertaV3",
                "DebertaV3Large",
                "DebertaV3Small",
                "DebertaV3XSmall",
                "BartBase",
                "BartLarge",
                "AlbertV2",
                "T5Base",
                "T5Large",
                "T5V1Base",
                "T5V1Large",
            )
        ),
    },
    user_attrs={},
    system_attrs={},
    intermediate_values={},
    trial_id=33,
    state=TrialState.COMPLETE,
    value=None,
)
